SELECT REPARTICION_USUARIO FROM historialoperaciones WHERE CODIGO_REPARTICION_DESTINO='CGPROV#MHYF' AND REPARTICION_USUARIO <>'CGPROV#MHYF' ;

SELECT REPARTICION_USUARIO, COUNT(*) AS cantidad FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO='CGPROV#MHYF' AND 
REPARTICION_USUARIO <>'CGPROV#MHYF' AND 
REPARTICION_USUARIO<>'TGPROV#MHYF' AND
SUBSTRING( fecha_operacion, 7, 4 ) = 2022  
GROUP BY REPARTICION_USUARIO ORDER BY cantidad DESC

SELECT * FROM historialoperaciones WHERE REPARTICION_USUARIO='TGPROV#MHYF' AND SUBSTRING( fecha_operacion, 7, 4 ) = 2022


;
