SELECT COUNT(*) FROM historialoperaciones WHERE SUBSTR(FECHA_OPERACION,4,4)='2021'

SELECT fecha_operacion, SUBSTR(fecha_operacion,7,4) AS anio, SUBSTR(fecha_operacion,4,2) AS mes FROM  historialoperaciones ;

SELECT * FROM historialoperaciones WHERE SUBSTR(FECHA_OPERACION,7,4)='2022' AND SUBSTR(fecha_operacion,4,2)='08' ;

SELECT COUNT(*) FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF'
AND
SUBSTR(FECHA_OPERACION,7,4)='2022' AND SUBSTR(fecha_operacion,4,2)='08' ; 8986
-- entrantes
SELECT * FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF'
AND
SUBSTR(FECHA_OPERACION,7,4)='2022' AND SUBSTR(fecha_operacion,4,2)='08' ; 

--entrantes por mes

SELECT SUBSTR(fecha_operacion,4,2) AS mes, COUNT(*) FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF'
AND
SUBSTR(FECHA_OPERACION,7,4)='2022' 
GROUP BY mes
 ; 
 
--AÑO Y MMES 
SELECT  SUBSTR(FECHA_OPERACION,7,4) AS ANIO, SUBSTR(fecha_operacion,4,2) AS mes, COUNT(*) FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF'


GROUP BY ANIO, mes
 ; 
 
 
 --SALIENTES POR AÑO Y MMES 
SELECT  SUBSTR(FECHA_OPERACION,7,4) AS ANIO, SUBSTR(fecha_operacion,4,2) AS mes, COUNT(*) FROM historialoperaciones 
WHERE 
CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF'


GROUP BY ANIO, mes
 ; 
  --ENTRANTES Y SALIENTES POR AÑO Y MMES 
SELECT 
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENES,

SUBSTR(FECHA_OPERACION,7,4) AS ANIO, 
SUBSTR(fecha_operacion,4,2) AS mes, 
COUNT(*) FROM historialoperaciones 

GROUP BY ANIO, mes
 ; 
 
  --ENTRANTES Y SALIENTES POR AÑO Y MMES 
SELECT 
SUBSTR(FECHA_OPERACION,7,4) AS ANIO, 
SUBSTR(fecha_operacion,4,2) AS mes, 
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENTES,

COUNT( *) AS TOTALES
FROM historialoperaciones 
GROUP BY ANIO, mes
 ;  
 
 
  --ENTRANTES Y SALIENTES POR AÑO Y MMES 
  
SELECT ANIO, MES, ENTRANTES, SALIENTES, ENTRANTES - SALIENTES AS DIFERENCIA, TOTALES FROM
(  
SELECT 
SUBSTR(FECHA_OPERACION,7,4) AS ANIO, 
SUBSTR(fecha_operacion,4,2) AS mes, 
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENTES

,

COUNT( *) AS TOTALES
FROM historialoperaciones 
GROUP BY ANIO, mes ) AS EXPEDIENTES
 ;  
 
 
 
   --ENTRANTES Y SALIENTES POR AÑO Y MMES 
  
SELECT ANIO, MES, ENTRANTES, SALIENTES, ENTRANTES - SALIENTES AS DIFERENCIA, TOTALES FROM
(  
SELECT 
SUBSTR(FECHA_OPERACION,7,4) AS ANIO, 
SUBSTR(fecha_operacion,4,2) AS mes, 
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENTES

,

COUNT( *) AS TOTALES
FROM historialoperaciones WHERE SUBSTR(fecha_operacion,7,4)='2022'
GROUP BY ANIO, mes ) AS EXPEDIENTES
 ;  
 
 
 SELECT ANIO, MES, ENTRANTES, SALIENTES, ENTRANTES - SALIENTES AS DIFERENCIA, TOTALES FROM
(  
SELECT 
SUBSTR(FECHA_OPERACION,7,4) AS ANIO, 
SUBSTR(fecha_operacion,4,2) AS mes, 
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENTES

,

COUNT( *) AS TOTALES
FROM historialoperaciones WHERE SUBSTR(fecha_operacion,7,4)='2022'
GROUP BY ANIO, mes ) AS EXPEDIENTES
 ;  
 
 
SELECT * FROM historialoperaciones WHERE CODIGO_REPARTICION_DESTINO='CGPROV#MHYF' AND
REPARTICION_USUARIO <>'CGPROV#MHYF'AND SUBSTR(FECHA_OPERACION,7,4) = '2022' AND SUBSTR(fecha_operacion,4,2) = '01' 

SELECT COUNT(*) AS cantidad, destinatario FROM historialoperaciones WHERE CODIGO_REPARTICION_DESTINO='CGPROV#MHYF' AND
REPARTICION_USUARIO <>'CGPROV#MHYF'AND SUBSTR(FECHA_OPERACION,7,4) = '2022' AND SUBSTR(fecha_operacion,4,2) = '01' 
GROUP BY destinatario ORDER BY cantidad DESC

   --ENTRANTES Y SALIENTES POR AÑO Y MMES 
  
SELECT ANIO, MES, ENTRANTES, SALIENTES, ENTRANTES - SALIENTES AS DIFERENCIA, TOTALES FROM
( 
 
SELECT 

 destinatario  ,
SUM( IF(CODIGO_REPARTICION_DESTINO='CGPROV#MHYF'
AND 
REPARTICION_USUARIO <>'CGPROV#MHYF', 1, 0 ) ) AS ENTRANTES,

SUM( IF( CODIGO_REPARTICION_DESTINO<>'CGPROV#MHYF'
AND 
REPARTICION_USUARIO ='CGPROV#MHYF', 1, 0 ) ) AS SALIENTES
,
COUNT( *) AS TOTALES
FROM historialoperaciones WHERE SUBSTR(fecha_operacion,7,4)='2022' AND SUBSTR(fecha_operacion,4,2) = '01' 
GROUP BY destinatario
ORDER BY salientes DESC


) AS EXPEDIENTES
 ;  

 